name: FuelLift
options:
  bundleIdPrefix: com.fuellift
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: "${DEVELOPMENT_TEAM}"
    MARKETING_VERSION: "1.0.1"
    CURRENT_PROJECT_VERSION: "1"

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"
  Lottie:
    url: https://github.com/airbnb/lottie-spm
    from: "4.4.0"
  SwiftUIShimmer:
    url: https://github.com/markiv/SwiftUI-Shimmer
    from: "1.4.0"
  ConfettiSwiftUI:
    url: https://github.com/simibac/ConfettiSwiftUI
    from: "1.1.0"

targets:
  FuelLift:
    type: application
    platform: iOS
    sources:
      - FuelLift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.fuellift.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Manual
        PROVISIONING_PROFILE_SPECIFIER: "match AppStore com.fuellift.app"
        CODE_SIGN_IDENTITY: "Apple Distribution"
    info:
      path: FuelLift/Resources/Info.plist
      properties:
        ANTHROPIC_API_KEY: $(ANTHROPIC_API_KEY)
        OPENAI_API_KEY: $(OPENAI_API_KEY)
        GEMINI_API_KEY: $(GEMINI_API_KEY)
        GOOGLE_PLACES_API_KEY: $(GOOGLE_PLACES_API_KEY)
        SPOONACULAR_API_KEY: $(SPOONACULAR_API_KEY)
        GOOGLE_CSE_ID: $(GOOGLE_CSE_ID)
        CFBundleIconName: AppIcon
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSHealthShareUsageDescription: "FuelLift reads your step count and active calories to adjust your daily calorie budget."
        NSHealthUpdateUsageDescription: "FuelLift writes your meals, workouts, and body weight to Apple Health."
        NSCameraUsageDescription: "FuelLift uses your camera to scan food and barcodes for instant calorie tracking."
        NSPhotoLibraryUsageDescription: "FuelLift uses your photo library to log food photos and progress pictures."
        NSLocationWhenInUseUsageDescription: "FuelLift uses your location to find healthy meal options at nearby restaurants."
        UIBackgroundModes:
          - remote-notification
        ITSAppUsesNonExemptEncryption: false
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseStorage
      - package: Firebase
        product: FirebaseMessaging
      - package: Lottie
        product: Lottie
      - package: SwiftUIShimmer
        product: Shimmer
      - package: ConfettiSwiftUI
        product: ConfettiSwiftUI
    entitlements:
      path: FuelLift/Resources/FuelLift.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
        aps-environment: development

  FuelLiftTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - FuelLiftTests
    dependencies:
      - target: FuelLift

  FuelLiftUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - FuelLiftUITests
    dependencies:
      - target: FuelLift

schemes:
  FuelLift:
    build:
      targets:
        FuelLift: all
        FuelLiftTests: [test]
        FuelLiftUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - FuelLiftTests
        - FuelLiftUITests
    archive:
      config: Release
