name: FuelLift
options:
  bundleIdPrefix: com.fuellift
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.4"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: "${DEVELOPMENT_TEAM}"
    CODE_SIGN_STYLE: Manual
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"
  Lottie:
    url: https://github.com/airbnb/lottie-spm
    from: "4.4.0"
  SwiftUIShimmer:
    url: https://github.com/markiv/SwiftUI-Shimmer
    from: "1.4.0"
  ConfettiSwiftUI:
    url: https://github.com/simibac/ConfettiSwiftUI
    from: "1.1.0"

targets:
  FuelLift:
    type: application
    platform: iOS
    sources:
      - FuelLift
    settings:
      base:
        INFOPLIST_FILE: FuelLift/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.fuellift.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseStorage
      - package: Firebase
        product: FirebaseMessaging
      - package: Lottie
        product: Lottie
      - package: SwiftUIShimmer
        product: Shimmer
      - package: ConfettiSwiftUI
        product: ConfettiSwiftUI
    entitlements:
      path: FuelLift/Resources/FuelLift.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
        aps-environment: development

  FuelLiftTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - FuelLiftTests
    dependencies:
      - target: FuelLift

  FuelLiftUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - FuelLiftUITests
    dependencies:
      - target: FuelLift

schemes:
  FuelLift:
    build:
      targets:
        FuelLift: all
        FuelLiftTests: [test]
        FuelLiftUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - FuelLiftTests
        - FuelLiftUITests
    archive:
      config: Release
